%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: 'Condense'

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  job_npm_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 24

    steps:
      - uses: actions/checkout@v6
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
        with:
          nodejs_version: ${{ matrix.node-version }}

      - run: ghciu condense

      - name: 'Pack the ghciu logs as an artifact.'
        if: '!cancelled()'
        uses: actions/upload-artifact@v6
        with:
          name: 'ghciu_logs.${{ env.GHCIU_TRACE_JOB }}'
          path: .ghciu/logs.local/



...
